on:
  pull_request: {}
  push:
    branches:
      - 'main'
jobs:
  build_cli:
    runs-on: docker
    steps:
      - name: Install capnproto
        run: apt update && apt install -yy capnproto

      - name: Check out repository code
        uses: https://code.forgejo.org/actions/checkout@v3

      - name: Set up Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Build with Cargo
        run: |
          source $HOME/.cargo/env
          cargo build 
