on:
  pull_request: {}
  push:
    branches:
      - 'main'
jobs:
  build_plugins:
    runs-on: docker
    steps:
      - name: Check out repository code
        uses: https://code.forgejo.org/actions/checkout@v3

      - name: Set up Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install cargo binstall
        run: |
          source $HOME/.cargo/env
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo component
        run: |
          source $HOME/.cargo/env
          cargo binstall cargo-component

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /bin

      - name: Build Plugins
        run: |
          source $HOME/.cargo/env
          just build-examples
          
