[package]
name = "bareops-hello-world-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
bareops-plugin-api = { path = "../../bareops-plugin-api"}

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "hello-world:plugin"

[package.metadata.component.dependencies]
